<?php
// $Id$

/**
 * @file
 * Provides a template for a blog website.
 */

/**
 * Implements hook_site_template_info().
 */
function blog_template_site_template_info() {
  $templates['blog'] = array(
    'name' => t('Blog site'),
    'description' => t('Create a blog; extend it to be much more.'),
    'features' => array(
      'blog_template_base_feature' => array('type' => SITE_TEMPLATE_FEATURE_REQUIRED),
      'site_template_disable_navigation_block' => array('type' => SITE_TEMPLATE_FEATURE_REQUIRED),
      'site_template_add_home_link' => array('type' => SITE_TEMPLATE_FEATURE_REQUIRED),
      'site_template_blog_feature' => array('type' => SITE_TEMPLATE_FEATURE_REQUIRED),
      'site_template_comment_feature' => array(),
      'site_template_comment_notify_feature' => array(),
      'site_template_follow_us_feature' => array(),
      'site_template_share_this_feature' => array(),
      'site_template_about_page' => array(),
      'site_template_contact_feature' => array(),
      'site_template_twitter_feature' => array(),
      'site_template_gallery_feature' => array(),
      'site_template_forum_feature' => array('type' => SITE_TEMPLATE_FEATURE_EXTRA),
      'site_template_rotating_banner_feature' => array('type' => SITE_TEMPLATE_FEATURE_EXTRA),
      'site_template_feedback_feature' => array('type' => SITE_TEMPLATE_FEATURE_EXTRA),
      'site_template_webforms_feature' => array('type' => SITE_TEMPLATE_FEATURE_EXTRA),
      // Features that must run at the end, to do things that require, e.g.,
      // all the template's content types to have been created or modules to
      // have been installed.
      'blog_template_remove_article_type' => array('type' => SITE_TEMPLATE_FEATURE_REQUIRED),
      'site_template_add_content_manager_role' => array('type' => SITE_TEMPLATE_FEATURE_REQUIRED),
      'site_template_add_blogger_role' => array('type' => SITE_TEMPLATE_FEATURE_REQUIRED),
      'site_template_update_node_types' => array('type' => SITE_TEMPLATE_FEATURE_REQUIRED),
    ),
    'editable variables' => array('theme_default'),
  );
  return $templates;
}
