<?php

/**
 * @file
 *   Provide test blocks.
 */

/**
 * Implements hook_system_theme_info().
 */
function block_test_system_theme_info() {
  $themes['block_test_theme'] = drupal_get_path('module', 'block_test') . '/themes/block_test_theme/block_test_theme.info';
  return $themes;
}

/**
 * Implements hook_block_info().
 */
function block_test_block_info() {
  $blocks['test_cache'] = array(
    'info' => t('Test block caching'),
    'cache' => variable_get('block_test_caching', DRUPAL_CACHE_PER_ROLE),
  );

  $blocks['test_html_id'] = array(
    'info' => t('Test block html id'),
  );

  $blocks['test_cache_with_assets'] = array(
    'info' => t('Test block caching with drupal_add_js'),
    'cache' => variable_get('block_test_caching', DRUPAL_CACHE_PER_ROLE),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function block_test_block_view($delta = 0) {
  switch ($delta) {
  case "test_cache_with_assets":
    drupal_add_js('misc/collapse.js');
    return array('content' => variable_get('block_test_content', ''));
  default:
    return array('content' => variable_get('block_test_content', ''));
  }
}
