#!/usr/bin/env bash
# $Id$
#
# Invoke this wrapper to use the drush that ships with the gardens codebase.
#
# This script is a simple wrapper that will run Drush with the most appropriate
# php executable it can find. It's derived from drush/drush but omits stuff
# speficic to windows, etc, and defines a list of allowed commands.
#

# Get the absolute path of this executable
ORIGDIR=$(pwd)
SELF_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P) && SELF_PATH=$SELF_PATH/$(basename -- "$0")

# Resolve symlinks - this is the equivalent of "readlink -f", but also works with non-standard OS X readlink.
while [ -h $SELF_PATH ]; do
    # 1) cd to directory of the symlink
    # 2) cd to the directory of where the symlink points
    # 3) Get the pwd
    # 4) Append the basename
    DIR=$(dirname -- "$SELF_PATH")
    SYM=$(readlink $SELF_PATH)
    SELF_PATH=$(cd $DIR && cd $(dirname -- "$SYM") && pwd)/$(basename -- "$SYM")
done
cd "$ORIGDIR"

# Build the path to drush.php.
SELF_DIR=$(dirname $SELF_PATH)
SCRIPT_PATH=$SELF_DIR/drush/drush.php
INCLUDE_PATH=$SELF_DIR/hosting-drush
ROOT_PATH=$SELF_DIR/docroot

# If not exported and term is set determine and export the number of columns.
if [ -z $COLUMNS ] && [ -n "$TERM" ]; then
  # Note to cygwin users: if you are getting "tput: command not found", 
  # install the ncurses package to get it.
  export COLUMNS=$(tput -T "$TERM" cols 2> /dev/null)
fi

# We run with straight php, which works on most systems.
exec php $SCRIPT_PATH --include=$INCLUDE_PATH --root=$ROOT_PATH -y --nocolor "$@"

