# grokked from the w3c table http://www.w3.org/TR/CSS2/propidx.html

elements = 'a', 'abbr', 'acronym', 'address', 'applet', 'area', 'b', 'base', 'basefont', 'bdo', 'big', 'blockquote', 'body', 'br', 'button', 'caption', 'center', 'cite', 'code', 'col', 'colgroup', 'dd', 'del', 'dfn', 'dir', 'div', 'dl', 'dt', 'em', 'fieldset', 'font', 'form', 'frame', 'frameset', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'head', 'hr', 'html', 'i', 'iframe', 'img', 'input', 'ins', 'isindex', 'kbd', 'label', 'legend', 'li', 'link', 'map', 'menu', 'meta', 'noframes', 'noscript', 'object', 'ol', 'optgroup', 'option', 'p', 'param', 'pre', 'q', 's', 'samp', 'script', 'select', 'small', 'span', 'strike', 'strong', 'style', 'sub', 'sup', 'table', 'tbody', 'td', 'textarea', 'tfoot', 'th', 'thead', 'title', 'tr', 'tt', 'u', 'ul', 'var'
attributes = ['background-attachment', 'background-color', 'background-image', 'background-position', 'background-repeat', 'background', 'border-collapse', 'border-color', 'border-spacing', 'border-style', "border-top-color' 'border-right-color' 'border-bottom-color' 'border-left-color", "border-top-style' 'border-right-style' 'border-bottom-style' 'border-left-style", "border-top-width' 'border-right-width' 'border-bottom-width' 'border-left-width", "border-top' 'border-right' 'border-bottom' 'border-left", 'border-width', 'border', 'bottom', 'caption-side', 'clear', 'clip', 'color', 'content', 'counter-increment', 'counter-reset', 'cursor', 'direction', 'display', 'empty-cells', 'float', 'font-family', 'font-size', 'font-style', 'font-variant', 'font-weight', 'font', 'height', 'left', 'letter-spacing', 'line-height', 'list-style-image', 'list-style-position', 'list-style-type', 'list-style', "margin-right' 'margin-left", "margin-top' 'margin-bottom", 'margin', 'max-height', 'max-width', 'min-height', 'min-width', 'orphans', 'outline-color', 'outline-style', 'outline-width', 'outline', 'overflow', "padding-top' 'padding-right' 'padding-bottom' 'padding-left", 'padding', 'page-break-after', 'page-break-before', 'page-break-inside', 'position', 'quotes', 'right', 'table-layout', 'text-align', 'text-decoration', 'text-indent', 'text-transform', 'top', 'unicode-bidi', 'vertical-align', 'visibility', 'white-space', 'widows', 'width', 'word-spacing', 'z-index']
defaults = ['scroll', 'transparent', 'none', '0% 0%', 'repeat', 'see individual properties', 'separate', 'see individual properties', '0', 'see individual properties', "black", 'none', 'medium', 'see individual properties', 'see individual properties', 'see individual properties', 'auto', 'top', 'none', 'auto', 'black', 'normal', 'none', 'none', 'auto', 'ltr', 'inline', 'show', 'none', 'Ariel', 'medium', 'normal', 'normal', 'normal', 'see individual properties', 'auto', 'auto', 'normal', 'normal', 'none', 'outside', 'disc', 'see individual properties', '0', '0', 'see individual properties', 'none', 'none', '0', '0', '2', 'invert', 'none', 'medium', 'see individual properties', 'visible', '0', 'see individual properties', 'auto', 'auto', 'auto', 'static', 'none', 'auto', 'auto', "left", 'none', '0', 'none', 'auto', 'normal', 'baseline', 'visible', 'normal', '2', 'auto', 'normal', 'auto']
applies = ['', '', '', '', '', '', "table,inline-table", '', "table,inline-table", '', '', '', '', '', '', '', '', "table-caption", 'block-level elements', 'absolutely positioned elements', '', '', '', '', '', '', '', "table-cell", '', '', '', '', '', '', '', '', '', '', '', "", "", "", "", 'table-caption, table, inline-table', 'table-caption, table, inline-table', 'table-caption, table and inline-table', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', "", '', '', '', '', '', '', "", '', '', '', '', '', '']

text = "#themebuilder-main "+", #themebuilder-main ".join(elements) + "{\n"
if 1:
    for i in range(len(attributes)):
        if applies[i]:
            continue
        if defaults[i] == "see individual properties":continue
        if "'" in attributes[i]:
            for attr in attributes[i].split("' '"):
                text += "  "+attr+": "+defaults[i]+";\n"
        else:
            text += "  "+attributes[i]+": "+defaults[i]+";\n"
    text += "}\n"
print text

