<?php

class ThemebuilderDirectory extends ThemebuilderAsset {

  public function __construct($theme_name) {
    parent::__construct($theme_name);
    $this->asset_name = $theme_name .".info";
  }

  public function renderString($theme_name = NULL) {
    $output = ";\$Id:\$\n"
      ."name = " .$this->theme_name ."\n"
      ."description = " .$this->theme_name ." was generated by Acquia's themebuilder.\n"
      ."version = VERSION\n"
      ."core = 7.x\n"
      ."engine = phptemplate\n"
      ."stylesheets[all][] = layout.css\n"
      ."stylesheets[all][] = custom.css\n";
    return $output;
  }

  public function getAllProperties() {
    return array('info');
  }

  public function copy($new_theme) {
    // Simply make a modified copy of the .info file.
    $asset = new ThemebuilderInfo($new_theme->getName());
    $asset->renderFile($new_theme->getPath());
  }

  public function delete($theme) {
    $path = $theme->getPath() .'/' .$this->getFilename();
    @unlink($path);
  }

  public static function getAssets($theme_name) {
    $result = array();
    $templates = db_select('themebuilder_template', 't')
      ->fields('t', array('selector'))
      ->condition('t.theme_name', $theme_name)
      ->execute();
    foreach ($templates as $template) {
      $result[] = new TemplateAsset($theme_name, $template->selector);
    }
    return $result;
  }


}
