# Settings for where to check the fields repository out from.  Fields is aka Acquia Hosting
fields:
  url : 'https://svn.acquia.com/repos/engineering/fields/branches/1.44'
  # Note that if the stage name is gsteamer-trunk, it will use the following.
  # @see GardensAutomation
#  url : 'https://svn.acquia.com/repos/engineering/fields/trunk'

# Where to check gardener out from.
# @TODO: Does it make sense to instead store this and the fields url in a "svn" block?
gardener:
  url : 'https://svn.acquia.com/repos/engineering/gardener/trunk'
  
gardens:
  url : 'https://svn.acquia.com/repos/engineering/gardens/trunk'  

# Where the fields repository is checked out to.
fields_root: '../fields'

# Settings for the EC2 server launch
availability_zone : us-east-1a

# The type of instance to launch for testing.
instance_type : m1.large

# Security
security_groups :
 fields_dev

# Is this required?
is_ubuntu: true

user_accounts :
  gardener_admin:
    user : admin
    password : ghetto#exits
  qatestuser:
    user: qatestuser
    password: ghetto#exits
  database:
     user: tester
     password: grape#fun

qa_admin_gmail:
  user: qa.admin@acquia.com
  password: D2bESEPTW!
  label: qa_auto_mail
  test_team: nik.gregory@acquia.com, marc.seeger@acquia.com, julian.lunger@acquia.com, emery.coxe@acquia.com
  gsteamer_daemon: steamer-gardens@acquia.com
  gardens_daemon: gardener@drupalgardens.com 
    

# What is iths?
max_sites : 100

#info for getting into basethemes site
#TODO: you should be able to get the server for the tangle you are interested in.
#TODO: I don't think this is even used.  I grepped for basethemes in all our gardens test... no reference other than config files.
basethemes :
  site : simpletest
  ssh_server : managed-47
  ssh_url : gsteamer.hosting.acquia.com
  user : basethemeupdater
  password : D2bESEPTW!

webdriver_config:
 local:
   browser_type: 'firefox'
   timeout: 3
 sauce:
   host: 'ondemand.saucelabs.com'
   port: 4444
   browser_type: {username: "acquia", access-key: "8a6674ed-b990-4ec4-92e1-5dba249b7a05", os: "XP", browser: "firefox", browser-version: "7."}
   timeout: 10
 sauceconnect:
   host: 'localhost'
   port: 4445
   browser_type: {username: "acquia", access-key: "8a6674ed-b990-4ec4-92e1-5dba249b7a05", os: "XP", browser: "firefox", browser-version: "7."}
   timeout: 10

selenium_config:
 local:
   host: 'localhost'
   port: 4444
   browser_type: '*firefox'
 sauce:
   host: 'saucelabs.com'
   port: 4444
   browser_type: {username: "acquia", access-key: "8a6674ed-b990-4ec4-92e1-5dba249b7a05", os: "Windows 2008", browser: "firefox", browser-version: "7."}
   timeout: 120
 sauceconnect:
   host: 'localhost'
   port: 4445
   browser_type: {username: "acquia", access-key: "8a6674ed-b990-4ec4-92e1-5dba249b7a05", os: "Windows 2008", browser: "firefox", browser-version: "7."}
   timeout: 120