# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1254103551);
user_pref("app.update.lastUpdateTime.background-update-timer", 1254103550);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1254103550);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1254103551);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1254103552);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage", "http://www.google.com/");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.0.14");
user_pref("extensions.enabledItems", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.0.14");
//user_pref("extensions.lastAppVersion", "3.0.14");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1256696494);
user_pref("browser.download.dir", "/tmp");
user_pref("browser.download.downloadDir", "/tmp");
user_pref("browser.download.folderList", 2);    // this can probably be 0, 1, or 2
user_pref("browser.download.manager.showWhenStarting", false);
