require 'rubygems'
require 'bundler/setup'
require "test/unit"
require 'acquia_qa/it'
require 'acquia_qa/log'
require 'acquia_qa/os'
require 'acquia_qa/ssh'
require 'acquia_qa/rake'
require 'acquia_qa/fields'
require 'acquia_qa/gardener'
require 'rake/testtask'
require 'acquia_qa/configuration'
require 'acquia_qa/svn'
require 'acquia_qa/site'
require 'relative'
include Acquia::Config
include OS
include Acquia::SSH
include DrupalSite
require '../lib/test_tasks'
require 'acquia_qa/gardens_automation'

# see:  http://rake.rubyforge.org/classes/Rake/TestTask.html
# to run one test only, call it like:
# rake run TEST=20_smoke_test.rb

#@TODO: paramaterize this
config_file = File.expand_path_relative_to_caller('./test_set.yaml')
remote_rakefile = File.expand_path_relative_to_caller('./remote-rakefile.rb')
GardensTestRun.instance.setup(config_file, remote_rakefile)
ENV['TEST_CONFIG_FILE'] = GardensTestRun.instance.config_file
ENV['AVAIL_ZONE'] = GardensTestRun.instance.config.availability_zone

raise 'You must set env var FIELDS_SSH_ID to use the rakefile' if ENV['FIELDS_SSH_ID'].nil?


desc "Run test cases ascii sorted"
Rake::TestTask.new('run') do |t|
  t.libs << "test:#{ENV['RUBYLIB']}"
  t.test_files = FileList['*_test.rb'].sort
  t.verbose = true
end
