<?php

/**
 * Implements hook_init().
 */
function acsf_init() {
  module_load_include('inc', 'acsf_events', 'classes/AcsfEvent');
  module_load_include('inc', 'acsf_events', 'classes/AcsfEventDispatcher');
  module_load_include('inc', 'acsf_events', 'classes/AcsfEventHandler');
  module_load_include('inc', 'acsf_log', 'classes/AcsfLog');
}

/**
 * Implements hook_modules_enabled().
 */
function acsf_modules_enabled($modules) {
  acsf_build_registry();
}

/**
 * Implements hook_menu_alter().
 */
function acsf_menu_alter() {
  acsf_build_registry();
}

/**
 * Builds the registry of ACSF compatible class files.
 */
function acsf_build_registry() {
  $registry = array();

  // Create a registry of ACSF compatible classes.
  $registry = module_invoke_all('acsf_registry');

  usort($registry['events'], 'acsf_registry_sort');

  variable_set('acsf_registry', $registry);
}

/**
 * Determines sort order for usort.
 */
function acsf_registry_sort($a, $b) {
  if (!isset($a['weight'])) {
    $a['weight'] = 0;
  }
  if (!isset($b['weight'])) {
    $b['weight'] = 0;
  }
  if ($a['weight'] == $b['weight']) {
      return 0;
  }
  return ($a['weight'] < $b['weight']) ? -1 : 1;
}

/**
 * Retrieves the registry of class files.
 *
 * @return Array
 */
function acsf_get_registry() {
  return variable_get('acsf_registry', NULL);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function acsf_form_system_site_maintenance_mode_alter(&$form, &$form_state) {
  // If we are in ACSF maintenance mode, don't let the admin uncheck the checkbox.
  $acsf_maintenance_time = variable_get('acsf_maintenance_time', 0);
  if ($acsf_maintenance_time && variable_get('maintenance_mode', 0)) {
    drupal_set_message(t('ACSF site maintenance in progress.'), 'warning');
    if (REQUEST_TIME > $acsf_maintenance_time) {
      // The update is taking longer than expected.
      drupal_set_message(t('The maintenance was expected to be done already - please be patient. Reload this page to see if maintenance is complete.'), 'warning');
    }
    else {
      // Never show an interval less than 1 minute.
      $remaining = format_interval(60 + $acsf_maintenance_time - REQUEST_TIME, 1);
      drupal_set_message(t('The maintenance should be completed within !interval. Reload this page to see if maintenance is complete.', array('!interval' => $remaining)), 'warning');
    }
    $form['maintenance_mode']['#disabled'] = TRUE;
  }
  $form['#submit'][] = 'acsf_system_site_maintenance_mode_submit';
}

/**
 * Submit handler for the system_site_maintenance_mode form.
 */
function acsf_system_site_maintenance_mode_submit(&$form, &$form_state) {
  // ACSF can force a site into maintenance mode, so when a site admin
  // puts their site into maintenance purposely, we need to track it.
  $maintenance_mode = (int) $form_state['values']['maintenance_mode'];
  if ($maintenance_mode) {
    variable_set('site_owner_maintenance_mode', $maintenance_mode);
  }
  else {
    variable_del('site_owner_maintenance_mode');
  }
}

/**
 * Implements hook_cron().
 */
function acsf_cron() {
  // Periodically refresh the site data.
  $site = AcsfSite::load();
  $refresh_age = time() - 86400 * 7;
  if ($site->last_sf_refresh < $refresh_age) {
    $site->refresh();
  }
}

