<?php

/**
 * @file
 * Enahancement in Warner SF package.
 */
/**
 * Implements hook_user_insert().
 */
function warner_utils_user_insert(&$edit, $account, $category) {
  watchdog('Registered Users', 'Successful registration: %username/%email/%ipaddr',
      array('%username' => $account->name, '%email' => $account->mail, 
      '%ipaddr' => $account->hostname), WATCHDOG_INFO);
}

/**
 * Implements hook_form_alter()
 * JIRA WMM-184
 */
function warner_utils_form_node_type_form_alter(&$form, $form_state) {
  if (module_exists('flippy')) {
    $form['flippy']['flippy_next_label']['#maxlength'] = 600;
    $form['flippy']['flippy_prev_label']['#maxlength'] = 600;
  }
}
