source :rubygems

gem "rake"
gem "net-ssh"
gem "net-scp"
gem "excon"

# Gems below are only needed because we require the monolithic gardens_automation.rb
gem "json"
gem "popen4"
gem "net-netrc"
gem "right_aws"
gem "selenium"
gem "selenium-webdriver"
gem "capybara-mechanize"
gem "relative"
gem "headless"
gem 'acquia_qa', :git => "ssh://git@git.acquia.com/mnt/git/repos/webdriver_qa.git"
