require 'rubygems'
require 'bundler/setup'
require 'rake/testtask'
require 'logger'
require '../helpers/gardens_automation.rb'
require '../helpers/qa_backdoor.rb'

include GardensAutomation::GardensHeadlessTestCase

# parse yaml files, setup @sut_url, $config and all that jazz
# comes from GardensHeadlessTestCase
self.setup()

@log = Logger.new(STDOUT)

desc 'Use qa backdoor to install the coder module and enable it'
task :setup_coder_review do
  parsed_sut_url = URI.parse($config["sut_url"])
  test_host = parsed_sut_url.host
  backdoor = QaBackdoor.new($config["sut_url"], { :logger => @log })

  backdoor.download_module("coder")
  backdoor.enable_module("coder")
  backdoor.enable_module("coder_review")
end

desc "Run test cases"
Rake::TestTask.new('run') do |t|
  #can be overridden by rake parameter TEST=
  t.test_files = FileList['*_test.rb'].sort
  t.verbose = true
end

