<?php
// $Id$

/**
 * @file
 * Provides a template for a campaign website.
 */

/**
 * Implements hook_site_template_info().
 */
function campaign_template_site_template_info() {
  $templates['campaign'] = array(
    'name' => t('Campaign site'),
    'description' => t('Build buzz quickly and get people to take action.'),
    'features' => array(
      'campaign_template_base_feature' => array('type' => SITE_TEMPLATE_FEATURE_REQUIRED),
      'site_template_sample_article' => array('type' => SITE_TEMPLATE_FEATURE_REQUIRED),
      'site_template_disable_navigation_block' => array('type' => SITE_TEMPLATE_FEATURE_REQUIRED),
      'site_template_add_home_link' => array('type' => SITE_TEMPLATE_FEATURE_REQUIRED),
      'site_template_comment_feature' => array(),
      'site_template_comment_notify_feature' => array(),
      'site_template_follow_us_feature' => array(),
      'site_template_share_this_feature' => array(),
      'site_template_about_page' => array(),
      'site_template_blog_feature' => array(),
      'site_template_contact_feature' => array(),
      'site_template_mailing_list_feature' => array(),
      'site_template_forum_feature' => array(),
      'site_template_news_page' => array(),
      'site_template_rotating_banner_feature' => array(),
      'site_template_gallery_feature' => array(),
      'site_template_faq_feature' => array('type' => SITE_TEMPLATE_FEATURE_EXTRA),
      'site_template_twitter_feature' => array('type' => SITE_TEMPLATE_FEATURE_EXTRA),
      'site_template_feedback_feature' => array('type' => SITE_TEMPLATE_FEATURE_EXTRA),
      'site_template_webforms_feature' => array('type' => SITE_TEMPLATE_FEATURE_EXTRA),
      // Features that must run at the end, to do things that require, e.g.,
      // all the template's content types to have been created or modules to
      // have been installed.
      'site_template_add_content_manager_role' => array('type' => SITE_TEMPLATE_FEATURE_REQUIRED),
      'site_template_add_blogger_role' => array('type' => SITE_TEMPLATE_FEATURE_REQUIRED),
      'site_template_add_editor_role' => array('type' => SITE_TEMPLATE_FEATURE_REQUIRED),
      'site_template_update_node_types' => array('type' => SITE_TEMPLATE_FEATURE_REQUIRED),
    ),
    'editable variables' => array('theme_default'),
  );
  return $templates;
}

class CampaignSiteTemplate extends DrupalSiteTemplate {
  /**
   * Site template callback for basic campaign site features.
   */
  public function campaign_template_base_feature_install(&$data, $features) {
    // Save the variables we will be modifying below.
    $data['variable_states'] = site_template_get_variable_states(array('site_slogan', 'theme_default'));

    // Enable the site slogan.
    variable_set('site_slogan', 'This is your site’s slogan. Edit, move or remove it as needed.');

    // Change the default theme.
    gardens_misc_replace_default_theme('campaign');
  }

  /**
   * Rollback function for basic campaign site features.
   */
  public function campaign_template_base_feature_rollback($data) {
    site_template_restore_variables_from_state($data['variable_states']);
  }

  /**
   * Override the preparation step for the "Comment" feature.
   */
  public function site_template_comment_feature_install_prepare(&$data, $features) {
    parent::site_template_comment_feature_install_prepare($data, $features);
    // Restrict the recent comments block to forum and blog pages and the front
    // page only.
    $data['block_data']['pages'] = array(
      '<front>',
      'blog',
      'blog/*',
      'forum',
      'forum/*',
    );
  }
}

