<?php

/**
 * @file
 * This module provides a centralized storage mechanism for all ACSF sensitive
 * variables that can be easily scrubbed.
 */

/**
 * Sets a named variable with an optional group.
 * 
 * @param String $name
 *   The name of the variable.
 * @param Unknown $value
 *   The value of the variable.
 * @param String $group
 *   The group name of the variable.
 */
function acsf_vset($name, $value, $group = NULL) {
  $merge = db_merge('acsf_variables')
    ->key(array('name' => $name))
    ->fields(array(
      'group_name' => $group,
      'value' => serialize($value),
    ))
    ->execute();

  return $merge;
}

/**
 * Retrieves a named variable.
 *
 * @param String $name
 *   The name of the variable.
 * @param Unknown $default
 *   The default value of the variable.
 *
 * @return Unknown
 */
function acsf_vget($name, $default = NULL) {
  $select = db_select('acsf_variables', 'v')
    ->fields('v', array('value'))
    ->condition('name', $name, '=')
    ->execute();

  if ($value = $select->fetchassoc()) {
    return unserialize($value['value']);
  }
  else {
    return $default;
  }
}

/**
 * Retrieves a group of variables.
 *
 * @param String $group
 *   The group name of the variables.
 * @param Unknown $default
 *   The default value of the group.
 *
 * @return Array
 */
function acsf_vget_group($group, $default = array()) {
  $return = array();

  $select = db_select('acsf_variables', 'v')
    ->fields('v', array('name', 'value'))
    ->condition('group_name', $group, '=')
    ->execute();

  while ($record = $select->fetchAssoc()) {
    $return[$record['name']] = unserialize($record['value']);
  }

  if (empty($return)) {
    return $default;
  }
  else {
    return $return;
  }
}

/**
 * Deletes a named variable.
 *
 * @param String $name
 *   The name of the variables.
 *
 * @return Bool
 */
function acsf_vdel($name) {
  $delete = db_delete('acsf_variables')
    ->condition('name', $name)
    ->execute();

  return $delete;
}
