<?php

/**
 * @file
 * Provides common logging for Acquia Cloud Site Factory operations.
 */

/**
 * Implements hook_watchdog().
 */
function acsf_log_watchdog($log_entry) {
  // Only escalate messages of certain severity levels.
  $severity_to_escalate = array(
    WATCHDOG_EMERGENCY,
    WATCHDOG_ALERT,
    WATCHDOG_CRITICAL,
  );

  if (in_array($log_entry['severity'], $severity_to_escalate)) {
    $record = array(
      'type' => 'watchdog',
      'message' => t($log_entry['message'], $log_entry['variables']),
      'level' => $log_entry['severity'],
      'timestamp' => REQUEST_TIME,
      'nid' => acsf_vget('acsf_site_nid', 0),
    );
    $acsf_log = new AcsfLog();
    $acsf_log->log($record);
  }
}

