<?php
/**
 * @file
 * Code for the wmg_magento_api feature.
 */

include_once 'wmg_magento_api.features.inc';

/**
 * Implements hook_menu().
 */
function wmg_magento_api_menu() {
  $items = array();
  $items['/admin/config/system/fanclub'] = array(
    'title' => t('Fan Club Magento API Settings'),
    'description' => 'Provides fanclub settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wmg_magento_api_settings_form'),
    'access arguments' => array('administer users'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements a system settings form.
 */
function wmg_magento_api_settings_form($form, &$form_state) {
  $roles = user_roles(TRUE);
  $form['fanclub_role'] = array(
    '#type' => 'fieldset',
    '#title' => t('Fanclub role settings'),
    '#weight' => 5,
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );
  $form['fanclub_role']['wmg_magento_api_fanclub_role'] = array(
    '#type' => 'select',
    '#title' => t('Fanclub role'),
    '#default_value' => variable_get('wmg_magento_api_fanclub_role', 1),
    '#required' => TRUE,
    '#options' => $roles,
    '#description' => t("Please select the role that will be used for fanclub access."),
  );
  return system_settings_form($form);
}

function wmg_magento_api_services_resources() {
  $user_resource = array(
    'subscription' => array(
      'actions' => array(
        'add' => array(
          'help' => 'Adds subscription for the user',
          'callback' => '_wmg_magento_api_services_resources_add',
          'args' => array(
            array(
              'name' => 'uid',
              'type' => 'int',
              'description' => 'A valid user id',
              'source' => array('data' => 'uid'),
              'optional' => FALSE,
            ),
          ),
          'access callback' => 'services_access_menu',
        ),
        'getstatus' => array(
          'help' => 'Adds subscription for the user',
          'callback' => '_wmg_magento_api_services_resources_get_status',
          'args' => array(
            array(
              'name' => 'uid',
              'type' => 'int',
              'description' => 'A valid user id',
              'source' => array('data' => 'uid'),
              'optional' => FALSE,
            ),
          ),
          'access callback' => 'services_access_menu',
        ),
      ),
    ),
  );
  return $user_resource;
}

/**
 * Callback for adding subscription.
 */
function _wmg_magento_api_services_resources_add($uid) {
  $fanclub_role = variable_get('wmg_magento_api_fanclub_role');
  $role = user_role_load($fanclub_role);
  $user = user_load($uid);
  $user->roles = $user->roles + array($role->rid => $role->name);
  user_save($user);
  return TRUE;
}

/**
 * Callback for getting subscription status.
 */
function _wmg_magento_api_services_resources_get_status($uid) {
  $user = user_load($uid);
  $fanclub_role = variable_get('wmg_magento_api_fanclub_role');
  if (array_key_exists($fanclub_role, $user->roles)) {
    return TRUE;
  }
  return FALSE;
}
